### ISSUE TITLE
Feature: roadgraph_samples/dir (data type: float) is required but could not be found. [Op:ParseExampleV2]

### ISSUE THREAD

**Issue by pc8504** [Tsinghua-MARS-Lab/InterSim#11]
Hi,
I would like to explore InterSim using the Waymo Open Dataset. Therefore I downloaded the "(gs://waymo_open_dataset_motion_v_1_2_1/uncompressed/scenario/testing)" part of the dataset. I updated the path in the config.py before starting "python sim.py --max_scenarios 5".

However I get a parsing error for the dataset files. Here is the full output log:

Data Loader Initialized Waymo:  0 0 0 None 0 None 150
2024-07-24 14:37:15,INFO:The hyperparameter of gym environment is list as blow
2024-07-24 14:37:15,INFO:frame rate is :10,
DriveEnv Environment initialized
Loading file from:  /ext2disk/wodm/scenaros/testing/testing.tfrecord-00000-of-00150  with index of  0
2024-07-24 14:37:15.380587: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-24 14:37:15.395741: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-07-24 14:37:15.412998: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2304000000 Hz
 with  307  scenarios and current is  0
2024-07-24 14:37:15.527174: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: roadgraph_samples/dir (data type: float) is required but could not be found.
Traceback (most recent call last):
  File "sim.py", line 243, in <module>
    main(args_p)
  File "sim.py", line 50, in main
    ended = env.reset(output_dir=output_dir)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
  File "/ext2disk/autobot/neolix/InterSim-code/simulator/interactive_sim/envs/drive.py", line 489, in reset
    loaded_scenario, new_files_loaded = self.data_loader.get_next(filter_config=self.filter_config,
  File "/ext2disk/autobot/neolix/InterSim-code/simulator/dataloader/DataLoaderWaymo.py", line 1114, in get_next
    data_to_return = self.get_datadic_fromTFRecord(data, process_intersection=process_intersection,
  File "/ext2disk/autobot/neolix/InterSim-code/simulator/dataloader/DataLoaderWaymo.py", line 626, in get_datadic_fromTFRecord
    parsed = tf.io.parse_single_example(data, features_description)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py", line 452, in parse_single_example_v2
    return parse_example_v2(serialized, features, example_names, name)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py", line 314, in parse_example_v2
    outputs = _parse_example_raw(serialized, example_names, params, name=name)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py", line 350, in _parse_example_raw
    outputs = gen_parsing_ops.parse_example_v2(
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 718, in parse_example_v2
    return parse_example_v2_eager_fallback(
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 812, in parse_example_v2_eager_fallback
    _result = _execute.execute(b"ParseExampleV2", num_sparse + len(sparse_types)
  File "/ext2disk/install/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: roadgraph_samples/dir (data type: float) is required but could not be found. [Op:ParseExampleV2]

**Comment by pc8504** [comment]
Do you know what the issue could be?
